### ISSUE TITLE
Sync endpoint

### ISSUE THREAD

**Issue by konklone** [sunlightlabs/scout#313]
Receive POSTs, with a secret key, with an array of active and inactive interests.

If the secret key is wrong for that service, 403.

If the user account does exist, but has a different service, 400.

If the user account does not exist, create it:
- with the provided 'service' field
- with the provided 'notifications' field
- with the provided email address
- as confirmed=true
- announcements and sunlight_announcements as false
- random password (unsynced with OS)

If the user account is invalid somehow, 400.

For active interests:
- look up the interest for that user - if it exists, do nothing
- if it doesn't exist, create it and save it

For inactive interests:
- look it up - if it doesn't exist, do nothing
- if it does exist, delete it _unless_ it has an updated_at timestamp that is newer than the timestamp provided for that interest

Check validity of each new interest, and only save/delete interests if  all new item interests successfully 'found' their referenced item. If they did not, 400 without any changes to the user's account or interests.

Request format:

```
email: jturk@sunlightfoundation.com
secret_key: whatever
service: openstates
notifications: email_daily
interests:
  active: true/false
  changed_at: [time it changed]

  interest_type: “item” 
  item_type: “state_bill” “state_legislator”
  item_id:  AKL0000001, etc.
                 OR
  interest_type: “search”
  search_type: “state_bills”
  in: “search text string”
  query_type: “simple” vs. “advanced”
  filters: {‘state’: ‘DE’} (could have others)
```
